---
consul_is_server: true
consul_node_name: "{{ ansible_fqdn }}"
consul_bind_address: "{{ ansible_eth1.ipv4.address }}"
consul_cert_file: "/etc/certs/cert.pem"
consul_key_file: "/etc/certs/key.pem"
consul_ca_file: "/etc/certs/ca.pem"
consul_install_nginx: false
consul_install_nginx_config: false
consul_enable_nginx_config: false
consul_client_address_bind: true
consul_client_address: "{{ ansible_eth1.ipv4.address }}"
consul_port_http: -1
consul_port_https: 8501
consul_encrypt: "X4SYOinf2pTAcAHRhpj7dA=="
docker_opts: >
          -H unix:///var/run/docker.sock
          -H tcp://{{ ansible_eth1.ipv4.address }}:2376
          --tlsverify
          --tlscacert=/etc/certs/ca.pem
          --tlscert=/etc/certs/cert.pem
          --tlskey=/etc/certs/key.pem
          --cluster-store=consul://{{ ansible_fqdn }}:8501
          --cluster-advertise=eth1:6969
          --cluster-store-opt kv.cacertfile=/etc/certs/ca.pem
          --cluster-store-opt kv.certfile=/etc/certs/cert.pem
          --cluster-store-opt kv.keyfile=/etc/certs/key.pem
