---
# file: swarm.yml
- hosts: all
  roles:
    - common

- hosts: swarm_admin
  roles:
    - cfssl

- hosts: swarm_nodes:swarm_manager
  roles:
    - docker-certs
    - ansible-consul
    - angstwad.docker_ubuntu
    - swarm-container
